# Generated by Django 4.0.2 on 2022-03-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
